const allKotobaData = [
    { jp: "おはようございます", hiragana: "おはようございます", romaji: "ohayou gozaimasu", meaning: "Selamat pagi", category: "SALAM & UCAPAN" },
    { jp: "こんにちは", hiragana: "こんにちは", romaji: "konnichiwa", meaning: "Selamat siang / Halo", category: "SALAM & UCAPAN" },
    { jp: "こんばんは", hiragana: "こんばんは", romaji: "konbanwa", meaning: "Selamat malam", category: "SALAM & UCAPAN" },
    { jp: "おやすみなさい", hiragana: "おやすみなさい", romaji: "oyasuminasai", meaning: "Selamat tidur", category: "SALAM & UCAPAN" },
    { jp: "さようなら", hiragana: "さようなら", romaji: "sayounara", meaning: "Selamat tinggal", category: "SALAM & UCAPAN" },
    { jp: "じゃあまた", hiragana: "じゃあまた", romaji: "jaa mata", meaning: "Sampai jumpa lagi", category: "SALAM & UCAPAN" },
    { jp: "また明日", hiragana: "またあした", romaji: "mata ashita", meaning: "Sampai jumpa besok", category: "WAKTU" },
    { jp: "ありがとうございます", hiragana: "ありがとうございます", romaji: "arigatou gozaimasu", meaning: "Terima kasih banyak", category: "SALAM & UCAPAN" },
    { jp: "どういたしまして", hiragana: "どういたしまして", romaji: "dou itashimashite", meaning: "Sama-sama", category: "SALAM & UCAPAN" },
    { jp: "すみません", hiragana: "すみません", romaji: "sumimasen", meaning: "Permisi / Maaf / Tolong", category: "SALAM & UCAPAN" },
    { jp: "ごめんなさい", hiragana: "ごめんなさい", romaji: "gomennasai", meaning: "Mohon maaf", category: "SALAM & UCAPAN" },
    { jp: "はじめまして", hiragana: "はじめまして", romaji: "hajimemashite", meaning: "Salam kenal (pertama kali)", category: "SALAM & UCAPAN" },
    { jp: "どうぞよろしく", hiragana: "どうぞよろしく", romaji: "douzo yoroshiku", meaning: "Mohon bantuannya", category: "SALAM & UCAPAN" },
    { jp: "いらっしゃいませ", hiragana: "いらっしゃいませ", romaji: "irasshaimase", meaning: "Selamat datang (toko)", category: "SALAM & UCAPAN" },
    { jp: "ただいま", hiragana: "ただいま", romaji: "tadaima", meaning: "Aku pulang", category: "SALAM & UCAPAN" },
    { jp: "おかえりなさい", hiragana: "おかえりなさい", romaji: "okaerinasai", meaning: "Selamat datang kembali", category: "SALAM & UCAPAN" },
    { jp: "行ってきます", hiragana: "いってきます", romaji: "itte kimasu", meaning: "Saya berangkat", category: "SALAM & UCAPAN" },
    { jp: "行っていらっしゃい", hiragana: "いっていらっしゃい", romaji: "itte irasshai", meaning: "Hati-hati di jalan", category: "SALAM & UCAPAN" },
    { jp: "いただきます", hiragana: "いただきます", romaji: "itadakimasu", meaning: "Selamat makan", category: "KATA KERJA" },
    { jp: "ごちそうさまでした", hiragana: "ごちそうさまでした", romaji: "gochisousama deshita", meaning: "Terima kasih atas makanannya", category: "SALAM & UCAPAN" },
    { jp: "お疲れ様です", hiragana: "おつかれさまです", romaji: "otsukaresama desu", meaning: "Terima kasih atas kerja kerasnya", category: "SALAM & UCAPAN" },
    { jp: "お大事に", hiragana: "おだいじに", romaji: "odai ni", meaning: "Semoga lekas sembuh", category: "SALAM & UCAPAN" },
    { jp: "気をつけて", hiragana: "きをつけて", romaji: "ki o tsukete", meaning: "Hati-hatilah", category: "SALAM & UCAPAN" },
    { jp: "なるほど", hiragana: "なるほど", romaji: "naruhodo", meaning: "Begitu ya / Oh begitu", category: "SALAM & UCAPAN" },
    { jp: "どうして", hiragana: "どうして", romaji: "doushite", meaning: "Mengapa / Kenapa", category: "SALAM & UCAPAN" },
    { jp: "家族", hiragana: "かぞく", romaji: "kazoku", meaning: "Keluarga", category: "BENDA & ORANG" },
    { jp: "父", hiragana: "ちち", romaji: "chichi", meaning: "Ayah (sendiri)", category: "BENDA & ORANG" },
    { jp: "お父さん", hiragana: "おとうさん", romaji: "otousan", meaning: "Ayah (orang lain / panggilan)", category: "BENDA & ORANG" },
    { jp: "母", hiragana: "はは", romaji: "haha", meaning: "Ibu (sendiri)", category: "BENDA & ORANG" },
    { jp: "お母さん", hiragana: "おかあさん", romaji: "okaasan", meaning: "Ibu (orang lain / panggilan)", category: "BENDA & ORANG" },
    { jp: "兄", hiragana: "あに", romaji: "ani", meaning: "Kakak laki-laki (sendiri)", category: "BENDA & ORANG" },
    { jp: "お兄さん", hiragana: "おにいさん", romaji: "oniisan", meaning: "Kakak laki-laki (orang lain)", category: "BENDA & ORANG" },
    { jp: "姉", hiragana: "あね", romaji: "ane", meaning: "Kakak perempuan (sendiri)", category: "BENDA & ORANG" },
    { jp: "お姉さん", hiragana: "おねえさん", romaji: "oneesan", meaning: "Kakak perempuan (orang lain)", category: "BENDA & ORANG" },
    { jp: "弟", hiragana: "おとうと", romaji: "otouto", meaning: "Adik laki-laki", category: "BENDA & ORANG" },
    { jp: "妹", hiragana: "いもうと", romaji: "imouto", meaning: "Adik perempuan", category: "BENDA & ORANG" },
    { jp: "祖父", hiragana: "そふ", romaji: "sofu", meaning: "Kakek (sendiri)", category: "BENDA & ORANG" },
    { jp: "おじいさん", hiragana: "おじいさん", romaji: "ojiisan", meaning: "Kakek / Pak Tua", category: "BENDA & ORANG" },
    { jp: "祖母", hiragana: "そぼ", romaji: "sobo", meaning: "Nenek (sendiri)", category: "BENDA & ORANG" },
    { jp: "おばあさん", hiragana: "おばあさん", romaji: "obaasan", meaning: "Nenek / Bu Tua", category: "BENDA & ORANG" },
    { jp: "子供", hiragana: "こども", romaji: "kodomo", meaning: "Anak-anak", category: "BENDA & ORANG" },
    { jp: "赤ちゃん", hiragana: "あかちゃん", romaji: "akachan", meaning: "Bayi", category: "BENDA & ORANG" },
    { jp: "自分", hiragana: "じぶん", romaji: "jibun", meaning: "Diri sendiri", category: "BENDA & ORANG" },
    { jp: "友達", hiragana: "ともだち", romaji: "tomodachi", meaning: "Teman", category: "BENDA & ORANG" },
    { jp: "恋人", hiragana: "こいびと", romaji: "koibito", meaning: "Pacar / Kekasih", category: "BENDA & ORANG" },
    { jp: "主人", hiragana: "しゅじん", romaji: "shujin", meaning: "Suami (sendiri)", category: "BENDA & ORANG" },
    { jp: "旦那", hiragana: "だんな", romaji: "danna", meaning: "Suami (panggilan akrab)", category: "BENDA & ORANG" },
    { jp: "妻", hiragana: "つま", romaji: "tsuma", meaning: "Istri (sendiri)", category: "BENDA & ORANG" },
    { jp: "奥さん", hiragana: "おくさん", romaji: "okusan", meaning: "Istri (orang lain)", category: "BENDA & ORANG" },
    { jp: "大人", hiragana: "おとな", romaji: "otona", meaning: "Orang dewasa", category: "BENDA & ORANG" },
    { jp: "私", hiragana: "わたし", romaji: "watashi", meaning: "Saya / Aku", category: "BENDA & ORANG" },
    { jp: "僕", hiragana: "ぼく", romaji: "boku", meaning: "Aku (biasanya digunakan laki-laki)", category: "BENDA & ORANG" },
    { jp: "俺", hiragana: "おれ", romaji: "ore", meaning: "Aku / Gue (kasual/laki-laki)", category: "BENDA & ORANG" },
    { jp: "あなた", hiragana: "あなた", romaji: "anata", meaning: "Anda / Kamu", category: "BENDA & ORANG" },
    { jp: "彼", hiragana: "かれ", romaji: "kare", meaning: "Dia (laki-laki) / Pacar pria", category: "BENDA & ORANG" },
    { jp: "彼女", hiragana: "かのじょ", romaji: "kanojo", meaning: "Dia (perempuan) / Pacar wanita", category: "BENDA & ORANG" },
    { jp: "私たち", hiragana: "わたしたち", romaji: "watashitachi", meaning: "Kami / Kita", category: "BENDA & ORANG" },
    { jp: "皆さん", hiragana: "みなさん", romaji: "minasan", meaning: "Sekalian / Hadirin / Semuanya", category: "BENDA & ORANG" },
    { jp: "誰", hiragana: "だれ", romaji: "dare", meaning: "Siapa", category: "BENDA & ORANG" },
    { jp: "どなた", hiragana: "どなた", romaji: "donata", meaning: "Siapa (bentuk sopan)", category: "BENDA & ORANG" },
    { jp: "男", hiragana: "おとこ", romaji: "otoko", meaning: "Laki-laki", category: "BENDA & ORANG" },
    { jp: "女", hiragana: "おんな", romaji: "onna", meaning: "Perempuan", category: "BENDA & ORANG" },
    { jp: "男の子", hiragana: "おとこのこ", romaji: "otokonoko", meaning: "Anak laki-laki", category: "BENDA & ORANG" },
    { jp: "女の子", hiragana: "おんなのこ", romaji: "onnanoko", meaning: "Anak perempuan", category: "BENDA & ORANG" },
    { jp: "外国人", hiragana: "がいこくじん", romaji: "gaikokujin", meaning: "Orang asing", category: "BENDA & ORANG" },
    { jp: "体", hiragana: "からだ", romaji: "karada", meaning: "Tubuh / Badan", category: "BENDA & ORANG" },
    { jp: "頭", hiragana: "あたま", romaji: "atama", meaning: "Kepala", category: "BENDA & ORANG" },
    { jp: "顔", hiragana: "かお", romaji: "kao", meaning: "Wajah", category: "BENDA & ORANG" },
    { jp: "目", hiragana: "め", romaji: "me", meaning: "Mata", category: "BENDA & ORANG" },
    { jp: "耳", hiragana: "みみ", romaji: "mimi", meaning: "Telinga", category: "BENDA & ORANG" },
    { jp: "鼻", hiragana: "はな", romaji: "hana", meaning: "Hidung", category: "BENDA & ORANG" },
    { jp: "口", hiragana: "くち", romaji: "kuchi", meaning: "Mulut", category: "BENDA & ORANG" },
    { jp: "歯", hiragana: "は", romaji: "ha", meaning: "Gigi", category: "BENDA & ORANG" },
    { jp: "首", hiragana: "くび", romaji: "kubi", meaning: "Leher", category: "BENDA & ORANG" },
    { jp: "手", hiragana: "て", romaji: "te", meaning: "Tangan", category: "BENDA & ORANG" },
    { jp: "指", hiragana: "ゆび", romaji: "yubi", meaning: "Jari", category: "BENDA & ORANG" },
    { jp: "足", hiragana: "あし", romaji: "ashi", meaning: "Kaki", category: "BENDA & ORANG" },
    { jp: "心", hiragana: "こころ", romaji: "kokoro", meaning: "Hati / Perasaan / Jiwa", category: "BENDA & ORANG" },
    { jp: "血", hiragana: "ち", romaji: "chi", meaning: "Darah", category: "BENDA & ORANG" },
    { jp: "骨", hiragana: "ほね", romaji: "hone", meaning: "Tulang", category: "BENDA & ORANG" },
    { jp: "ご飯", hiragana: "ごはん", romaji: "gohan", meaning: "Nasi / Makanan", category: "BENDA & ORANG" },
    { jp: "水", hiragana: "みず", romaji: "mizu", meaning: "Air (dingin/tawar)", category: "BENDA & ORANG" },
    { jp: "お湯", hiragana: "おゆ", romaji: "oyu", meaning: "Air panas", category: "BENDA & ORANG" },
    { jp: "お茶", hiragana: "おちゃ", romaji: "ocha", meaning: "Teh hijau", category: "BENDA & ORANG" },
    { jp: "紅茶", hiragana: "こうちゃ", romaji: "koucha", meaning: "Teh hitam", category: "BENDA & ORANG" },
    { jp: "コーヒー", hiragana: "コーヒー", romaji: "koohii", meaning: "Kopi", category: "BENDA & ORANG" },
    { jp: "牛乳", hiragana: "ぎゅうにゅう", romaji: "gyuunyuu", meaning: "Susu sapi", category: "BENDA & ORANG" },
    { jp: "ジュース", hiragana: "ジュース", romaji: "juusu", meaning: "Jus", category: "BENDA & ORANG" },
    { jp: "ビール", hiragana: "ビール", romaji: "biiru", meaning: "Bir", category: "BENDA & ORANG" },
    { jp: "酒", hiragana: "さけ", romaji: "sake", meaning: "Alkohol / Sake", category: "BENDA & ORANG" },
    { jp: "肉", hiragana: "にく", romaji: "niku", meaning: "Daging", category: "BENDA & ORANG" },
    { jp: "魚", hiragana: "さかな", romaji: "sakana", meaning: "Ikan", category: "BENDA & ORANG" },
    { jp: "野菜", hiragana: "やさい", romaji: "yasai", meaning: "Sayuran", category: "BENDA & ORANG" },
    { jp: "果物", hiragana: "くだもの", romaji: "kudamono", meaning: "Buah-buahan", category: "BENDA & ORANG" },
    { jp: "卵", hiragana: "たまご", romaji: "tamago", meaning: "Telur", category: "BENDA & ORANG" },
    { jp: "パン", hiragana: "パン", romaji: "pan", meaning: "Roti", category: "BENDA & ORANG" },
    { jp: "塩", hiragana: "しお", romaji: "shio", meaning: "Garam", category: "BENDA & ORANG" },
    { jp: "砂糖", hiragana: "さとう", romaji: "satou", meaning: "Gula", category: "BENDA & ORANG" },
    { jp: "醤油", hiragana: "しょうゆ", romaji: "shouyu", meaning: "Kecap asin Jepang", category: "BENDA & ORANG" },
    { jp: "料理", hiragana: "りょうり", romaji: "ryouri", meaning: "Masakan / Memasak", category: "KATA KERJA" },
    { jp: "朝ご飯", hiragana: "あさごはん", romaji: "asagohan", meaning: "Sarapan", category: "BENDA & ORANG" },
    { jp: "昼ご飯", hiragana: "ひるごはん", romaji: "hirugohan", meaning: "Makan siang", category: "BENDA & ORANG" },
    { jp: "晩ご飯", hiragana: "ばんごはん", romaji: "bangohan", meaning: "Makan malam", category: "BENDA & ORANG" },
    { jp: "食堂", hiragana: "しょくどう", romaji: "shokudou", meaning: "Kantin / Rumah makan kecil", category: "BENDA & ORANG" },
    { jp: "レストラン", hiragana: "レストラン", romaji: "resutoran", meaning: "Restoran", category: "BENDA & ORANG" },
    { jp: "服", hiragana: "ふく", romaji: "fuku", meaning: "Pakaian / Baju", category: "BENDA & ORANG" },
    { jp: "シャツ", hiragana: "シャツ", romaji: "shatsu", meaning: "Kemeja / Kaos", category: "BENDA & ORANG" },
    { jp: "ズボン", hiragana: "ズボン", romaji: "zubon", meaning: "Celana", category: "BENDA & ORANG" },
    { jp: "靴", hiragana: "くつ", romaji: "kutsu", meaning: "Sepatu", category: "BENDA & ORANG" },
    { jp: "靴下", hiragana: "くつした", romaji: "kutsushita", meaning: "Kaos kaki", category: "BENDA & ORANG" },
    { jp: "帽子", hiragana: "ぼうし", romaji: "boushi", meaning: "Topi", category: "BENDA & ORANG" },
    { jp: "眼鏡", hiragana: "めがね", romaji: "megane", meaning: "Kacamata", category: "BENDA & ORANG" },
    { jp: "手袋", hiragana: "てぶくろ", romaji: "tebukuro", meaning: "Sarung tangan", category: "BENDA & ORANG" },
    { jp: "財布", hiragana: "さいふ", romaji: "saifu", meaning: "Dompet", category: "BENDA & ORANG" },
    { jp: "傘", hiragana: "かさ", romaji: "kasa", meaning: "Payung", category: "BENDA & ORANG" },
    { jp: "鞄", hiragana: "かばん", romaji: "kaban", meaning: "Tas", category: "BENDA & ORANG" },
    { jp: "指輪", hiragana: "ゆびわ", romaji: "yubiwa", meaning: "Cincin", category: "BENDA & ORANG" },
    { jp: "時計", hiragana: "とけい", romaji: "tokei", meaning: "Jam", category: "WAKTU" },
    { jp: "着物", hiragana: "きもの", romaji: "kimono", meaning: "Kimono", category: "BENDA & ORANG" },
    { jp: "制服", hiragana: "せいふく", romaji: "seifuku", meaning: "Seragam", category: "BENDA & ORANG" },
    { jp: "家", hiragana: "いえ", romaji: "ie", meaning: "Rumah", category: "BENDA & ORANG" },
    { jp: "部屋", hiragana: "へや", romaji: "heya", meaning: "Kamar / Ruangan", category: "BENDA & ORANG" },
    { jp: "台所", hiragana: "だいどころ", romaji: "daidokoro", meaning: "Dapur", category: "BENDA & ORANG" },
    { jp: "風呂", hiragana: "ふろ", romaji: "furo", meaning: "Kamar mandi / Bathtub", category: "BENDA & ORANG" },
    { jp: "トイレ", hiragana: "トイレ", romaji: "toire", meaning: "Toilet", category: "BENDA & ORANG" },
    { jp: "庭", hiragana: "にわ", romaji: "niwa", meaning: "Taman rumah / Halaman", category: "BENDA & ORANG" },
    { jp: "窓", hiragana: "まど", romaji: "mado", meaning: "Jendela", category: "BENDA & ORANG" },
    { jp: "ドア", hiragana: "ドア", romaji: "doa", meaning: "Pintu", category: "BENDA & ORANG" },
    { jp: "床", hiragana: "ゆか", romaji: "yuka", meaning: "Lantai", category: "BENDA & ORANG" },
    { jp: "壁", hiragana: "かべ", romaji: "kabe", meaning: "Dinding", category: "BENDA & ORANG" },
    { jp: "机", hiragana: "つくえ", romaji: "tsukue", meaning: "Meja belajar/kerja", category: "BENDA & ORANG" },
    { jp: "椅子", hiragana: "いす", romaji: "isu", meaning: "Kursi", category: "BENDA & ORANG" },
    { jp: "ベッド", hiragana: "ベッド", romaji: "beddo", meaning: "Tempat tidur", category: "BENDA & ORANG" },
    { jp: "布団", hiragana: "ふとん", romaji: "futon", meaning: "Kasur tradisional Jepang", category: "BENDA & ORANG" },
    { jp: "本棚", hiragana: "ほんだな", romaji: "hondana", meaning: "Rak buku", category: "BENDA & ORANG" },
    { jp: "テレビ", hiragana: "テレビ", romaji: "terebi", meaning: "Televisi", category: "BENDA & ORANG" },
    { jp: "ラジオ", hiragana: "ラジオ", romaji: "rajio", meaning: "Radio", category: "BENDA & ORANG" },
    { jp: "カメラ", hiragana: "カメラ", romaji: "kamera", meaning: "Kamera", category: "BENDA & ORANG" },
    { jp: "携帯", hiragana: "けいたい", romaji: "keitai", meaning: "Ponsel / Handphone", category: "BENDA & ORANG" },
    { jp: "電話", hiragana: "でんわ", romaji: "denwa", meaning: "Telepon", category: "BENDA & ORANG" },
    { jp: "パソコン", hiragana: "パソコン", romaji: "pasokon", meaning: "Komputer jinjing / Laptop", category: "BENDA & ORANG" },
    { jp: "冷蔵庫", hiragana: "れいぞうこ", romaji: "reizouko", meaning: "Kulkas", category: "BENDA & ORANG" },
    { jp: "洗濯機", hiragana: "せんたくき", romaji: "sentakuki", meaning: "Mesin cuci", category: "BENDA & ORANG" },
    { jp: "掃除機", hiragana: "そうじき", romaji: "soujiki", meaning: "Vacuum cleaner / Penyedot debu", category: "BENDA & ORANG" },
    { jp: "エアコン", hiragana: "エアコン", romaji: "eakon", meaning: "AC / Pendingin ruangan", category: "BENDA & ORANG" },
    { jp: "鍵", hiragana: "かぎ", romaji: "kagi", meaning: "Kunci", category: "BENDA & ORANG" },
    { jp: "箱", hiragana: "はこ", romaji: "hako", meaning: "Kotak / Box", category: "BENDA & ORANG" },
    { jp: "袋", hiragana: "ふくろ", romaji: "fukuro", meaning: "Kantong / Tas plastik", category: "BENDA & ORANG" },
    { jp: "紙", hiragana: "かみ", romaji: "kami", meaning: "Kertas", category: "BENDA & ORANG" },
    { jp: "鉛筆", hiragana: "えんぴつ", romaji: "enpitsu", meaning: "Pensil", category: "BENDA & ORANG" },
    { jp: "飲む", hiragana: "のむ", romaji: "nomu", meaning: "Minum", category: "KATA KERJA" },
    { jp: "読む", hiragana: "よむ", romaji: "yomu", meaning: "Membaca", category: "KATA KERJA" },
    { jp: "書く", hiragana: "かく", romaji: "kaku", meaning: "Menulis", category: "KATA KERJA" },
    { jp: "話す", hiragana: "はなす", romaji: "hanasu", meaning: "Berbicara", category: "KATA KERJA" },
    { jp: "行く", hiragana: "いく", romaji: "iku", meaning: "Pergi", category: "KATA KERJA" },
    { jp: "来る", hiragana: "くる", romaji: "kuru", meaning: "Datang", category: "KATA KERJA" },
    { jp: "帰る", hiragana: "かえる", romaji: "kaeru", meaning: "Pulang", category: "KATA KERJA" },
    { jp: "買う", hiragana: "かう", romaji: "kau", meaning: "Membeli", category: "KATA KERJA" },
    { jp: "売る", hiragana: "うる", romaji: "uru", meaning: "Menjual", category: "KATA KERJA" },
    { jp: "待つ", hiragana: "まつ", romaji: "matsu", meaning: "Menunggu", category: "KATA KERJA" },
    { jp: "持つ", hiragana: "もつ", romaji: "motsu", meaning: "Mempunyai / Membawa", category: "KATA KERJA" },
    { jp: "会う", hiragana: "あう", romaji: "au", meaning: "Bertemu", category: "KATA KERJA" },
    { jp: "聞く", hiragana: "きく", romaji: "kiku", meaning: "Mendengar / Bertanya", category: "KATA KERJA" },
    { jp: "働く", hiragana: "はたらく", romaji: "hataraku", meaning: "Bekerja", category: "KATA KERJA" },
    { jp: "泳ぐ", hiragana: "およぐ", romaji: "oyogu", meaning: "Berenang", category: "KATA KERJA" },
    { jp: "遊ぶ", hiragana: "あそぶ", romaji: "asobu", meaning: "Bermain", category: "KATA KERJA" },
    { jp: "死ぬ", hiragana: "しぬ", romaji: "shinu", meaning: "Mati / Meninggal", category: "KATA KERJA" },
    { jp: "立つ", hiragana: "たつ", romaji: "tatsu", meaning: "Berdiri", category: "KATA KERJA" },
    { jp: "座る", hiragana: "すわる", romaji: "suwaru", meaning: "Duduk", category: "KATA KERJA" },
    { jp: "入る", hiragana: "はいる", romaji: "hairu", meaning: "Masuk", category: "KATA KERJA" },
    { jp: "出る", hiragana: "でる", romaji: "deru", meaning: "Keluar", category: "KATA KERJA" },
    { jp: "乗る", hiragana: "のる", romaji: "noru", meaning: "Naik (kendaraan)", category: "KATA KERJA" },
    { jp: "降りる", hiragana: "おりる", romaji: "oriru", meaning: "Turun (kendaraan)", category: "KATA KERJA" },
    { jp: "取る", hiragana: "とる", romaji: "toru", meaning: "Mengambil", category: "KATA KERJA" },
    { jp: "撮る", hiragana: "とる", romaji: "toru", meaning: "Memotret / Mengambil foto", category: "KATA KERJA" },
    { jp: "わかる", hiragana: "わかる", romaji: "wakaru", meaning: "Mengerti / Paham", category: "KATA KERJA" },
    { jp: "知る", hiragana: "しる", romaji: "shiru", meaning: "Mengetahui / Kenal", category: "KATA KERJA" },
    { jp: "歩く", hiragana: "あるく", romaji: "aruku", meaning: "Berjalan", category: "KATA KERJA" },
    { jp: "走る", hiragana: "はしる", romaji: "hashiru", meaning: "Berlari", category: "KATA KERJA" },
    { jp: "曲がる", hiragana: "まがる", romaji: "magaru", meaning: "Belok", category: "KATA KERJA" },
    { jp: "洗う", hiragana: "あらう", romaji: "arau", meaning: "Mencuci", category: "KATA KERJA" },
    { jp: "歌う", hiragana: "うたう", romaji: "utau", meaning: "Bernyanyi", category: "KATA KERJA" },
    { jp: "弾く", hiragana: "ひく", romaji: "hiku", meaning: "Memetik (alat musik)", category: "KATA KERJA" },
    { jp: "引く", hiragana: "ひく", romaji: "hiku", meaning: "Menarik", category: "KATA KERJA" },
    { jp: "脱ぐ", hiragana: "ぬぐ", romaji: "nugu", meaning: "Melepas (pakaian/sepatu)", category: "KATA KERJA" },
    { jp: "消す", hiragana: "けす", romaji: "kesu", meaning: "Memadamkan / Menghapus", category: "KATA KERJA" },
    { jp: "貸す", hiragana: "かす", romaji: "kasu", meaning: "Meminjamkan", category: "KATA KERJA" },
    { jp: "借りる", hiragana: "かりる", romaji: "kariru", meaning: "Meminjam", category: "KATA KERJA" },
    { jp: "返す", hiragana: "かえす", romaji: "kaesu", meaning: "Mengembalikan", category: "KATA KERJA" },
    { jp: "送る", hiragana: "おくる", romaji: "okuru", meaning: "Mengirim / Mengantar", category: "KATA KERJA" },
    { jp: "食べる", hiragana: "たべる", romaji: "taberu", meaning: "Makan", category: "KATA KERJA" },
    { jp: "見る", hiragana: "みる", romaji: "miru", meaning: "Melihat / Menonton", category: "KATA KERJA" },
    { jp: "寝る", hiragana: "ねる", romaji: "neru", meaning: "Tidur", category: "KATA KERJA" },
    { jp: "起きる", hiragana: "おきる", romaji: "okiru", meaning: "Bangun tidur", category: "KATA KERJA" },
    { jp: "開ける", hiragana: "あける", romaji: "akeru", meaning: "Membuka", category: "KATA KERJA" },
    { jp: "閉める", hiragana: "しめる", romaji: "shimeru", meaning: "Menutup (pintu/jendela)", category: "KATA KERJA" },
    { jp: "締める", hiragana: "しめる", romaji: "shimeru", meaning: "Mengencangkan / Memakai dasi", category: "KATA KERJA" },
    { jp: "教える", hiragana: "おしえる", romaji: "oshieru", meaning: "Mengajar / Memberi tahu", category: "KATA KERJA" },
    { jp: "覚える", hiragana: "おぼえる", romaji: "oboeru", meaning: "Mengingat / Menghafal", category: "KATA KERJA" },
    { jp: "忘れる", hiragana: "わすれる", romaji: "wasureru", meaning: "Lupa", category: "KATA KERJA" },
    { jp: "着る", hiragana: "きる", romaji: "kiru", meaning: "Memakai (pakaian atas)", category: "KATA KERJA" },
    { jp: "浴びる", hiragana: "あびる", romaji: "abiru", meaning: "Mandinya (mengguyur badan)", category: "KATA KERJA" },
    { jp: "始める", hiragana: "はじめる", romaji: "hajimeru", meaning: "Memulai", category: "KATA KERJA" },
    { jp: "終わる", hiragana: "おわる", romaji: "owaru", meaning: "Selesai", category: "KATA KERJA" },
    { jp: "変える", hiragana: "かえる", romaji: "kaeru", meaning: "Mengubah / Menukar", category: "KATA KERJA" },
    { jp: "考える", hiragana: "かんがえる", romaji: "kangaeru", meaning: "Berpikir", category: "KATA KERJA" },
    { jp: "見せる", hiragana: "みせる", romaji: "miseru", meaning: "Memperlihatkan", category: "KATA KERJA" },
    { jp: "調べる", hiragana: "しらべる", romaji: "shiraberu", meaning: "Memeriksa / Menyelidiki", category: "KATA KERJA" },
    { jp: "集める", hiragana: "あつめる", romaji: "atsumeru", meaning: "Mengumpulkan", category: "KATA KERJA" },
    { jp: "決める", hiragana: "きめる", romaji: "kimeru", meaning: "Memutuskan", category: "KATA KERJA" },
    { jp: "する", hiragana: "する", romaji: "suru", meaning: "Melakukan", category: "KATA KERJA" },
    { jp: "勉強する", hiragana: "べんきょうする", romaji: "benkyou suru", meaning: "Belajar", category: "KATA KERJA" },
    { jp: "散歩する", hiragana: "さんぽする", romaji: "sanpo suru", meaning: "Berjalan-jalan", category: "KATA KERJA" },
    { jp: "旅行する", hiragana: "りょこうする", romaji: "ryokou suru", meaning: "Berwisata / Bepergian", category: "KATA KERJA" },
    { jp: "買い物する", hiragana: "かいものする", romaji: "kaimono suru", meaning: "Berbelanja", category: "KATA KERJA" },
    { jp: "食事する", hiragana: "しょくじする", romaji: "shokuji suru", meaning: "Makan / Santap", category: "KATA KERJA" },
    { jp: "電話する", hiragana: "でんわする", romaji: "denwa suru", meaning: "Menelpon", category: "KATA KERJA" },
    { jp: "掃除する", hiragana: "そうじする", romaji: "souji suru", meaning: "Membersihkan", category: "KATA KERJA" },
    { jp: "洗濯する", hiragana: "せんたくする", romaji: "sentaku suru", meaning: "Mencuci pakaian", category: "KATA KERJA" },
    { jp: "料理する", hiragana: "りょうりする", romaji: "ryouri suru", meaning: "Memasak", category: "KATA KERJA" },
    { jp: "練習する", hiragana: "れんしゅうする", romaji: "renshuu suru", meaning: "Berlatih", category: "KATA KERJA" },
    { jp: "運動する", hiragana: "うんどうする", romaji: "undou suru", meaning: "Berolahraga", category: "KATA KERJA" },
    { jp: "運転する", hiragana: "うんてんする", romaji: "unten suru", meaning: "Menyetir", category: "KATA KERJA" },
    { jp: "仕事する", hiragana: "しごとする", romaji: "shigoto suru", meaning: "Bekerja", category: "KATA KERJA" },
    { jp: "案内する", hiragana: "あんないする", romaji: "annai suru", meaning: "Memandu / Menunjukkan jalan", category: "KATA KERJA" },
    { jp: "紹介する", hiragana: "しょうかいする", romaji: "shoukai suru", meaning: "Memperkenalkan", category: "KATA KERJA" },
    { jp: "計画する", hiragana: "けいかくする", romaji: "keikaku suru", meaning: "Merencanakan", category: "KATA KERJA" },
    { jp: "相談する", hiragana: "そうだんする", romaji: "soudan suru", meaning: "Berkonsultasi / Berdiskusi", category: "KATA KERJA" },
    { jp: "注意する", hiragana: "ちゅういする", romaji: "chuui suru", meaning: "Berhati-hati / Memperhatikan", category: "KATA KERJA" },
    { jp: "説明する", hiragana: "せつめいする", romaji: "setsumei suru", meaning: "Menjelaskan", category: "KATA KERJA" },
    { jp: "住む", hiragana: "すむ", romaji: "sumu", meaning: "Tinggal / Berdomisili", category: "KATA KERJA" },
    { jp: "生まれる", hiragana: "うまれる", romaji: "umareru", meaning: "Lahir", category: "KATA KERJA" },
    { jp: "降る", hiragana: "ふる", romaji: "furu", meaning: "Turun (hujan/salju)", category: "KATA KERJA" },
    { jp: "曇る", hiragana: "くもる", romaji: "kumoru", meaning: "Berawan", category: "KATA KERJA" },
    { jp: "晴れる", hiragana: "はれる", romaji: "hareru", meaning: "Cerah", category: "KATA KERJA" },
    { jp: "吹く", hiragana: "ふく", romaji: "fuku", meaning: "Bertiup (angin)", category: "KATA KERJA" },
    { jp: "咲く", hiragana: "さく", romaji: "saku", meaning: "Mekar (bunga)", category: "KATA KERJA" },
    { jp: "散る", hiragana: "ちる", romaji: "chiru", meaning: "Gugur / Berjatuhan", category: "KATA KERJA" },
    { jp: "並ぶ", hiragana: "ならぶ", romaji: "narabu", meaning: "Berbaris / Berjejer", category: "KATA KERJA" },
    { jp: "並べる", hiragana: "ならべる", romaji: "naraberu", meaning: "Menjajarkan / Menyusun", category: "KATA KERJA" },
    { jp: "止まる", hiragana: "とまる", romaji: "tomaru", meaning: "Berhenti (otomatis)", category: "KATA KERJA" },
    { jp: "止める", hiragana: "とめる", romaji: "tomeru", meaning: "Menghentikan", category: "KATA KERJA" },
    { jp: "変わる", hiragana: "かわる", romaji: "kawaru", meaning: "Berubah", category: "KATA KERJA" },
    { jp: "直す", hiragana: "なおす", romaji: "naosu", meaning: "Memperbaiki", category: "KATA KERJA" },
    { jp: "直る", hiragana: "なおる", romaji: "naoru", meaning: "Sembuh / Diperbaiki", category: "KATA KERJA" },
    { jp: "見つかる", hiragana: "みつかる", romaji: "mitsukaru", meaning: "Ditemukan", category: "KATA KERJA" },
    { jp: "見つける", hiragana: "みつける", romaji: "mitsukeru", meaning: "Menemukan", category: "KATA KERJA" },
    { jp: "落とする", hiragana: "おとす", romaji: "otosu", meaning: "Menjatuhkan", category: "KATA KERJA" },
    { jp: "落ちる", hiragana: "おちる", romaji: "ochiru", meaning: "Jatuh", category: "KATA KERJA" },
    { jp: "大きい", hiragana: "おおきい", romaji: "ookii", meaning: "Besar", category: "KATA SIFAT" },
    { jp: "小さい", hiragana: "ちいさい", romaji: "chiisai", meaning: "Kecil", category: "KATA SIFAT" },
    { jp: "高い", hiragana: "たかい", romaji: "takai", meaning: "Mahal / Tinggi", category: "KATA SIFAT" },
    { jp: "安い", hiragana: "やすい", romaji: "yasui", meaning: "Murah", category: "KATA SIFAT" },
    { jp: "新しい", hiragana: "あたらしい", romaji: "atarashii", meaning: "Baru", category: "KATA SIFAT" },
    { jp: "古い", hiragana: "ふるい", romaji: "furui", meaning: "Lama / Tua (benda)", category: "KATA SIFAT" },
    { jp: "良い", hiragana: "いい / よい", romaji: "ii / yoi", meaning: "Bagus / Baik", category: "KATA SIFAT" },
    { jp: "悪い", hiragana: "わるい", romaji: "warui", meaning: "Buruk / Jahat", category: "KATA SIFAT" },
    { jp: "暑い", hiragana: "あつい", romaji: "atsui", meaning: "Panas (cuaca/suhu)", category: "KATA SIFAT" },
    { jp: "熱い", hiragana: "あつい", romaji: "atsui", meaning: "Panas (benda/sentuhan)", category: "KATA SIFAT" },
    { jp: "冷たい", hiragana: "つめたい", romaji: "tsumetai", meaning: "Dingin (benda/sentuhan)", category: "KATA SIFAT" },
    { jp: "寒い", hiragana: "さむい", romaji: "samui", meaning: "Dingin (cuaca/udara)", category: "KATA SIFAT" },
    { jp: "暖かい", hiragana: "あたたかい", romaji: "atatakai", meaning: "Hangat", category: "KATA SIFAT" },
    { jp: "涼しい", hiragana: "すずしい", romaji: "suzushii", meaning: "Sejuk", category: "KATA SIFAT" },
    { jp: "美味しい", hiragana: "おいしい", romaji: "oishii", meaning: "Enak / Lezat", category: "KATA SIFAT" },
    { jp: "まずい", hiragana: "まずい", romaji: "mazui", meaning: "Tidak enak", category: "KATA SIFAT" },
    { jp: "甘い", hiragana: "あまい", romaji: "amai", meaning: "Manis", category: "KATA SIFAT" },
    { jp: "辛い", hiragana: "からい", romaji: "karai", meaning: "Pedas / Asin", category: "KATA SIFAT" },
    { jp: "塩辛い", hiragana: "しおからい", romaji: "shiokarai", meaning: "Asin", category: "KATA SIFAT" },
    { jp: "苦い", hiragana: "にがい", romaji: "nigai", meaning: "Pahit", category: "KATA SIFAT" },
    { jp: "酸っぱい", hiragana: "すっぱい", romaji: "suppai", meaning: "Asam", category: "KATA SIFAT" },
    { jp: "重い", hiragana: "おもい", romaji: "omoi", meaning: "Berat", category: "KATA SIFAT" },
    { jp: "軽い", hiragana: "かるい", romaji: "karui", meaning: "Ringan", category: "KATA SIFAT" },
    { jp: "明るい", hiragana: "あかるい", romaji: "akarui", meaning: "Terang / Ceria", category: "KATA SIFAT" },
    { jp: "暗い", hiragana: "くらい", romaji: "kurai", meaning: "Gelap", category: "KATA SIFAT" },
    { jp: "白い", hiragana: "しろい", romaji: "shiroi", meaning: "Putih", category: "KATA SIFAT" },
    { jp: "黒い", hiragana: "くろい", romaji: "kuroi", meaning: "Hitam", category: "KATA SIFAT" },
    { jp: "赤い", hiragana: "あかい", romaji: "akai", meaning: "Merah", category: "KATA SIFAT" },
    { jp: "青い", hiragana: "あおい", romaji: "aoi", meaning: "Biru / Hijau (alam)", category: "KATA SIFAT" },
    { jp: "黄色い", hiragana: "きいろい", romaji: "kiiroi", meaning: "Kuning", category: "KATA SIFAT" },
    { jp: "長い", hiragana: "ながい", romaji: "nagai", meaning: "Panjang", category: "KATA SIFAT" },
    { jp: "短い", hiragana: "みじかい", romaji: "mijikai", meaning: "Pendek", category: "KATA SIFAT" },
    { jp: "近い", hiragana: "ちかい", romaji: "chikai", meaning: "Dekat", category: "KATA SIFAT" },
    { jp: "遠い", hiragana: "とおい", romaji: "tooi", meaning: "Jauh", category: "KATA SIFAT" },
    { jp: "早い", hiragana: "はやい", romaji: "hayai", meaning: "Cepat / Awal (waktu)", category: "KATA SIFAT" },
    { jp: "速い", hiragana: "はやい", romaji: "hayai", meaning: "Cepat (kecepatan)", category: "KATA SIFAT" },
    { jp: "遅い", hiragana: "おそい", romaji: "osoi", meaning: "Lambat / Terlambat", category: "KATA SIFAT" },
    { jp: "広い", hiragana: "ひろい", romaji: "hiroi", meaning: "Luas", category: "KATA SIFAT" },
    { jp: "狭い", hiragana: "せまい", romaji: "semai", meaning: "Sempit", category: "KATA SIFAT" },
    { jp: "太い", hiragana: "ふとい", romaji: "futoi", meaning: "Gemuk / Tebal", category: "KATA SIFAT" },
    { jp: "細い", hiragana: "ほそい", romaji: "hosoi", meaning: "Kurus / Tipis", category: "KATA SIFAT" },
    { jp: "若い", hiragana: "わかい", romaji: "wakai", meaning: "Muda", category: "KATA SIFAT" },
    { jp: "忙しい", hiragana: "いそがしい", romaji: "isogashii", meaning: "Sibuk", category: "KATA SIFAT" },
    { jp: "楽しい", hiragana: "たのしい", romaji: "tanoshii", meaning: "Menyenangkan", category: "KATA SIFAT" },
    { jp: "面白い", hiragana: "おもしろい", romaji: "omoshiroi", meaning: "Menarik / Lucu", category: "KATA SIFAT" },
    { jp: "つまらない", hiragana: "つまらない", romaji: "tsumaranai", meaning: "Membosankan", category: "KATA SIFAT" },
    { jp: "難しい", hiragana: "むずかしい", romaji: "muzukashii", meaning: "Sulit / Susah", category: "KATA SIFAT" },
    { jp: "易しい", hiragana: "やさしい", romaji: "yasashii", meaning: "Mudah / Gampang", category: "KATA SIFAT" },
    { jp: "優しい", hiragana: "やさしい", romaji: "yasashii", meaning: "Baik hati / Lembut", category: "KATA SIFAT" }
    { jp: "痛い", hiragana: "いたい", romaji: "itai", meaning: "Sakit", category: "KATA SIFAT" },
    { jp: "欲しい", hiragana: "ほしい", romaji: "hoshii", meaning: "Ingin (benda)", category: "KATA SIFAT" },
    { jp: "嬉しい", hiragana: "うれしい", romaji: "ureshii", meaning: "Senang / Gembira", category: "KATA SIFAT" },
    { jp: "悲しい", hiragana: "かなしい", romaji: "kanashii", meaning: "Sedih", category: "KATA SIFAT" },
    { jp: "寂しい", hiragana: "さびしい", romaji: "sabishii", meaning: "Kesepian", category: "KATA SIFAT" },
    { jp: "強い", hiragana: "つよい", romaji: "tsuyoi", meaning: "Kuat", category: "KATA SIFAT" },
    { jp: "弱い", hiragana: "よわい", romaji: "yowai", meaning: "Lemah", category: "KATA SIFAT" },
    { jp: "危ない", hiragana: "あぶない", romaji: "abunai", meaning: "Bahaya", category: "KATA SIFAT" },
    { jp: "うるさい", hiragana: "うるさい", romaji: "urusai", meaning: "Bising / Berisik", category: "KATA SIFAT" },
    { jp: "きたない", hiragana: "きたない", romaji: "kitanai", meaning: "Kotor", category: "KATA SIFAT" },
    { jp: "眠い", hiragana: "ねむい", romaji: "nemui", meaning: "Mengantuk", category: "KATA SIFAT" },
    { jp: "静かな", hiragana: "しずかな", romaji: "shizuka na", meaning: "Tenang / Sunyi", category: "KATA SIFAT" },
    { jp: "賑やかな", hiragana: "にぎやかな", romaji: "nigiyaka na", meaning: "Ramai / Rame", category: "KATA SIFAT" },
    { jp: "綺麗な", hiragana: "きれいな", romaji: "kirei na", meaning: "Cantik / Bersih", category: "KATA SIFAT" },
    { jp: "親切な", hiragana: "しんせつな", romaji: "shinsetsu na", meaning: "Ramah / Baik hati", category: "KATA SIFAT" },
    { jp: "有名な", hiragana: "ゆうめいな", romaji: "yuumei na", meaning: "Terkenal", category: "KATA SIFAT" },
    { jp: "元気な", hiragana: "げんきな", romaji: "genki na", meaning: "Sehat / Bugar", category: "KATA SIFAT" },
    { jp: "暇な", hiragana: "ひまな", romaji: "hima na", meaning: "Luang / Senggang", category: "KATA SIFAT" },
    { jp: "便利な", hiragana: "べんりな", romaji: "benri na", meaning: "Praktis / Berguna", category: "KATA SIFAT" },
    { jp: "不便な", hiragana: "ふべんな", romaji: "fuben na", meaning: "Tidak praktis", category: "KATA SIFAT" },
    { jp: "好きな", hiragana: "すきな", romaji: "suki na", meaning: "Suka", category: "KATA SIFAT" },
    { jp: "嫌な", hiragana: "いやな", romaji: "iya na", meaning: "Tidak suka / Menyebalkan", category: "KATA SIFAT" },
    { jp: "嫌いな", hiragana: "きらいな", romaji: "kirai na", meaning: "Benci / Tidak suka", category: "KATA SIFAT" },
    { jp: "上手な", hiragana: "じょうずな", romaji: "jouzu na", meaning: "Pintar / Mahir", category: "KATA SIFAT" },
    { jp: "下手な", hiragana: "へたな", romaji: "heta na", meaning: "Tidak mahir / Payah", category: "KATA SIFAT" },
    { jp: "大切な", hiragana: "たいせつな", romaji: "taisetsu na", meaning: "Penting / Berharga", category: "KATA SIFAT" },
    { jp: "大事な", hiragana: "だいじな", romaji: "daiji na", meaning: "Penting / Istimewa", category: "KATA SIFAT" },
    { jp: "大変な", hiragana: "たいへんな", romaji: "taihen na", meaning: "Berat / Susah / Luar biasa", category: "KATA SIFAT" },
    { jp: "色々な", hiragana: "いろいろな", romaji: "iroiro na", meaning: "Berbagai macam", category: "KATA SIFAT" },
    { jp: "特別な", hiragana: "とくべつな", romaji: "tokubetsu na", meaning: "Khusus / Spesial", category: "KATA SIFAT" },
    { jp: "簡単な", hiragana: "かんたんな", romaji: "kantan na", meaning: "Mudah / Sederhana", category: "KATA SIFAT" },
    { jp: "複雑な", hiragana: "ふくざつな", romaji: "fukuzatsu na", meaning: "Rumit / Kompleks", category: "KATA SIFAT" },
    { jp: "安心な", hiragana: "あんしんな", romaji: "anshin na", meaning: "Tenang / Lega / Aman", category: "KATA SIFAT" },
    { jp: "安全な", hiragana: "あんぜんな", romaji: "anzen na", meaning: "Aman", category: "KATA SIFAT" },
    { jp: "危険な", hiragana: "きけんな", romaji: "kiken na", meaning: "Berbahaya", category: "KATA SIFAT" },
    { jp: "自由な", hiragana: "じゆうな", romaji: "jiyuu na", meaning: "Bebas", category: "KATA SIFAT" },
    { jp: "真面目な", hiragana: "まじめな", romaji: "majime na", meaning: "Rajin / Serius", category: "KATA SIFAT" },
    { jp: "熱心な", hiragana: "ねっしんな", romaji: "nesshin na", meaning: "Antusias / Tekun / Semangat", category: "KATA SIFAT" },
    { jp: "立派な", hiragana: "りっぱな", romaji: "rippa na", meaning: "Megah / Hebat / Luar biasa", category: "KATA SIFAT" },
    { jp: "十分な", hiragana: "じゅうぶんな", romaji: "juubun na", meaning: "Cukup", category: "KATA SIFAT" },
    { jp: "必要な", hiragana: "ひつような", romaji: "hitsuyou na", meaning: "Perlu / Diperlukan", category: "KATA SIFAT" },
    { jp: "残念な", hiragana: "ざんねんな", romaji: "zannen na", meaning: "Disayangkan", category: "KATA SIFAT" },
    { jp: "変な", hiragana: "へんな", romaji: "hen na", meaning: "Aneh", category: "KATA SIFAT" },
    { jp: "上等な", hiragana: "じょうとうな", romaji: "joutou na", meaning: "Kualitas bagus / Mutu tinggi", category: "KATA SIFAT" },
    { jp: "適当な", hiragana: "てきとうな", romaji: "tekitou na", meaning: "Cocok / Asal-asalan", category: "KATA SIFAT" },
    { jp: "失礼な", hiragana: "しつれいな", romaji: "shitsurei na", meaning: "Tidak sopan / Kurang ajar", category: "KATA SIFAT" },
    { jp: "丈夫な", hiragana: "じょうぶな", romaji: "joubu na", meaning: "Kuat / Awet / Sehat", category: "KATA SIFAT" },
    { jp: "丁寧な", hiragana: "ていねいな", romaji: "teinei na", meaning: "Sopan / Hati-hati (teliti)", category: "KATA SIFAT" },
    { jp: "不親切な", hiragana: "ふしんせつな", romaji: "fushinsetsu na", meaning: "Tidak ramah", category: "KATA SIFAT" },
    { jp: "平和な", hiragana: "へいわな", romaji: "heiwa na", meaning: "Damai", category: "KATA SIFAT" },
